# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 6, 49, 49, 466869), verbose_name='date published'),
        ),
    ]
