# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20160511_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
    ]
