# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_product_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='keywords',
            new_name='keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='', max_length=30000),
        ),
    ]
